add_library(weave_tcp STATIC src/windows/tcp.cpp)
weave_module(tcp)
target_link_libraries(weave_tcp PUBLIC weave::io PRIVATE ws2_32 mswsock)
target_include_directories(weave_tcp PRIVATE ../io/src)
target_compile_definitions(weave_tcp PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _WIN32_WINNT=0x0602)
if(WEAVE_BUILD_TESTS)
  weave_add_test(weave_tcp_tests tests/tcp.cpp)
  target_link_libraries(weave_tcp_tests PRIVATE weave::tcp)
  target_include_directories(weave_tcp_tests PRIVATE ${PROJECT_SOURCE_DIR}/test_support)
  target_compile_definitions(weave_tcp_tests PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _WIN32_WINNT=0x0602)
endif()
