if(WIN32)
  add_library(weave_local STATIC src/windows/local.cpp)
else()
  add_library(weave_local STATIC src/linux/local.cpp)
endif()
weave_module(local)
target_link_libraries(weave_local PUBLIC weave::io)
target_include_directories(weave_local PRIVATE ../io/src)
if(WIN32)
  target_link_libraries(weave_local PRIVATE ws2_32 mswsock)
  target_compile_definitions(weave_local PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX _WIN32_WINNT=0x0A00)
else()
  target_link_libraries(weave_local PRIVATE PkgConfig::LIBURING)
endif()

if(WEAVE_BUILD_TESTS)
  weave_add_test(weave_local_tests tests/local.cpp)
  target_link_libraries(weave_local_tests PRIVATE weave::local)
  if(TARGET weave_runtime)
    target_link_libraries(weave_local_tests PRIVATE weave::runtime)
    target_compile_definitions(weave_local_tests PRIVATE WEAVE_LOCAL_TEST_RUNTIME=1)
  endif()
endif()
